services:
  app:
    container_name: app
    build:
      context: docker
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    expose:
      - 8080:8080
    tty: true